config/routes.rb
Rails.application.routes.draw do
  devise_for :users  , :path_prefix => 'my', :controllers => {:registrations => "registrations"}
  devise_scope :user do
    get 'login', to: 'devise/session#new'
  end
  resources :users
  delete 'users/:id/edit', to: 'users#delete'
 
  get 'informes/index'
  get 'informes/new'
  resources :informacion
  resources :facultads
  delete 'facultads/:id/edit', to: 'facultads#delete'
  resources :alertas
  resources :estudiantes
  delete 'estudiantes/:id/edit', to: 'estudiantes#delete'
  resources :informes
  delete 'informes/:id/edit', to: 'informes#delete'
  resources :rols
  resources :tutores
  delete 'tutores/:id/edit', to: 'tutores#delete'
  resources :carreras
  delete 'carreras/:id/edit', to: 'carreras#delete'
  resources :page

  

  devise_scope :user do
    authenticated :user do
      root 'page#index', as: :authenticated_root
    end
  end
  unauthenticated do
    root 'devise/sessions#new', as: :unauthenticated_root
  end



  




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/alerta.rb
class Alerta < ApplicationRecord
  belongs_to :informe
end

app/models/alertum.rb
class Alertum < ApplicationRecord
  has_one :prioridad
  belongs_to :informe
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/carrera.rb
class Carrera < ApplicationRecord
  belongs_to :facultad
  has_many :estudiantes
  has_many :users
  validates :nombrecarrera, :codigo,:facultad_id, :presence => true
  validates :nombrecarrera, length: {minimum: 2, maximum: 50}
  validates :codigo, length: {is:5}, uniqueness: true,numericality: {greater_than: 0}

end

app/models/destroy.rb
class Destroy < ApplicationRecord
end

app/models/estudiante.rb
class Estudiante < ApplicationRecord
  has_and_belongs_to_many :users, optional:true
  belongs_to :carrera
  has_many :informes
  
  validates :nombreestudiante, presence:  { message: 'Ingrese el primer nombre '}, length: {in: 3..40, message:'El nombre debe ser de mínimo largo 3'}, format: {with: /\A[a-zA-Z\s]+\z/,
  message: "Se permiten solo letras en los nombres"}
  validates :direccion, presence: {message: 'Ingrese Dirección'},length: {in: 8..40, message:'El nombre debe ser de mínimo largo 20'}
  validates :comuna, presence: {message: 'Ingrese Comuna'}
  validates :apellidopa, presence: { message: 'Ingrese el primer apellido'}, length: {in: 3..20, message:'El apellido debe ser de mínimo largo 3'}, format: {with: /\A[a-zA-Z\s]+\z/,
  message: "Se permiten solo letras en los apellidos"}
  validates :apellidoma, presence: { message: 'Ingrese el segundo apellido'}, length: {in: 3..20, message:'El apellido debe ser de mínimo largo 3'}, format: {with: /\A[a-zA-Z\s]+\z/,
  message: "Se permiten solo letras en los apellidos"}
  include RunCl::ActAsRun
  Run.valid? '11.1111.111-1'
  Run.format('11.111.111-1')
  validates :rut , presence: { message: 'Ingrese un rut'}, uniqueness: true
  has_run_cl :rut
 validate :unique_rut
  validates :fecha_nacimiento , presence: {message: 'Ingrese la fecha de nacimiento'}
  validates :telefono, presence: {message: 'Ingrese Telefono'}, length: {is: 9, message:'Largo debe ser 9'}
  validate :fecha_de_nacimiento_debe_ser_en_pasado
  validate :edadminima


def fecha_de_nacimiento_debe_ser_en_pasado
  if fecha_nacimiento.present? && fecha_nacimiento >= Date.today
    errors.add(:fecha_nacimiento, "debe ser anterior a la fecha de hoy")
  end
end


def edadminima
   if fecha_nacimiento.present? && fecha_nacimiento >= 17.year.ago
        errors.add(:fecha_nacimiento, "debe ser mayor de 17 años")
   end
end
def unique_rut
  self.errors.add(:name, 'Rut ya existente') if User.where(rut: self.rut).exists?
end

def fullname
  "#{nombreestudiante} #{apellidopa} #{apellidoma}" 

end
end

app/models/facultad.rb
class Facultad < ApplicationRecord
    has_many :carreras
    has_many :users
    validates :nombrefacultad, :presence => true,length: {minimum:3,maximum: 50 },uniqueness: true
end

app/models/informe.rb
class Informe < ApplicationRecord
  has_one :alerta
  belongs_to :estudiante
  belongs_to :user
  validates :nota1,:nota2,:nota3 ,:nota4,:nota5,:nota6,:nota7,:nota8,:nota9,:nota10,:nota11,:nota12,:nota13,:nota14,:nota15,:observacion, :presence => true
  validates :observacion ,length: {minimum: 10,maximum: 2500}
end

app/models/informe_tutor.rb
class InformeTutor < ApplicationRecord
   
    validates :objetivo, presence:true
    validates :observaciones, presence:true



end

app/models/rol.rb
class Rol < ApplicationRecord
    has_many :users
    validates :descripcion, :uniqueness => true
end

app/models/supervisar.rb
class Supervisar < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable
  has_and_belongs_to_many :estudiantes, optional:true
  belongs_to :facultad, optional:true
  belongs_to :rol, optional:true
  belongs_to :carrera, optional:true
  validates :rol_id, presence: true
  validates :estado, :inclusion => {:in=> [true,false]}
  validates :nombre, presence:  { message: 'Ingrese el primer nombre '} , length: {in: 3..40, message:'El nombre debe ser de mínimo largo 3'}, format: {with: /\A[a-zA-Z\s]+\z/,
  message: "Se permiten solo letras en los nombres"}
  validates :apellidopa, presence: { message: 'Ingrese el primer apellido'}, length: {in: 3..20, message:'El apellido debe ser de mínimo largo 3'}, format: {with: /\A[a-zA-Z\s]+\z/,message: "Se permiten solo letras en los apellidos"}
  validates :apellidoma, presence: { message: 'Ingrese el segundo apellido'}, length: {in: 3..20, message:'El apellido debe ser de mínimo largo 3'}, format: {with: /\A[a-zA-Z\s]+\z/, message: "Se permiten solo letras en los apellidos"}
  include RunCl::ActAsRun
  Run.valid? '11.1111.111-1'
  Run.format('11.111.111-1')
  validates :rut , presence: { message: 'Ingrese un rut'}, uniqueness: true
  has_run_cl :rut
 validate :unique_rut
 validates :facultad_id, presence:true
validates :fecha_nacimiento , presence: {message: 'Ingrese la fecha de nacimiento'}
validates :telefono, presence: {message: 'Ingrese Telefono'}, length: {is: 9, message:'Largo debe ser 9'}
validate :fecha_de_nacimiento_debe_ser_en_pasado
validate :edadminima



def fecha_de_nacimiento_debe_ser_en_pasado
  if fecha_nacimiento.present? && fecha_nacimiento >= Date.today
  errors.add(:fecha_nacimiento, "debe ser anterior a la fecha de hoy")
  end
end


def edadminima
   if fecha_nacimiento.present? && fecha_nacimiento >= 18.year.ago
        errors.add(:fecha_nacimiento, "debe ser mayor de 18 años")
   end
end




def active_for_authentication?
  super && self.estado
end

def inactive_message
  "Perdon , su cuenta ha sido desactivada"
end



def unique_rut
  self.errors.add(:name, 'Rut ya existente') if Estudiante.where(rut: self.rut).exists?
end




def fullname
  "#{nombre} #{apellidopa} #{apellidoma}" 

end
  

validates :facultad_id, presence:true
validates :rol_id, presence:true






end

app/controllers/menu_controller.rb
class MenuController < ApplicationController
end

app/controllers/page_controller.rb
class PageController < ApplicationController
	before_action :authenticate_user!
	layout "prueba"
  def index
  end
end

app/controllers/rols_controller.rb
class RolsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_facultad, only: [:show,:delete,:edit,:update]

  layout "prueba"
    def index
        @roles=Rol.all
        @rols= Rol.new
        end
      
        def show
         @rol= Rol.find(params[:id])
        end 
      
        def new
      
         @rols= Rol.new
      
        end

  def create
    @rol= Rol.new(rol_params)
    if @rol.save
      redirect_to rols_path ,success:"Se creo correctamente"
    else
      render 'new' , danger: "Ingrese datos válidos"
    end
  end
private
def rol_params
  params.require(:rol).permit(:descripcion, :estado)
end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carreras_helper.rb
module CarrerasHelper
end

app/helpers/informacion_helper.rb
module InformacionHelper
end

app/helpers/informes_helper.rb
module InformesHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/informes/index.html.erb
<h1>Informes <% if current_user.rol.descripcion!='Administrador'%><%= current_user.rol.descripcion%><%end%></h1>
<%= link_to 'Generar Informe', new_informe_path, :class => "btn btn-info" %>
<Table class="table">
  <tr>
    <thead class="thead-dark">
    <th>N° </th>
    <th> Nombre Estudiante </th>
    <th> Carrera </th>
    <th> Nombre Profesional</th>
    <th> Estado </th>
    <th> Opciones </th>
  </thead>
  </tr>

  <% @informes.each do |t| %>
  
  <% if (t.user.rol.descripcion==current_user.rol.descripcion && t.estado==true) || current_user.rol.descripcion=='Administrador' %>
  <tr>
  <td><%= t.id %></td>
  <td><%= t.estudiante.nombreestudiante %> <%= t.estudiante.apellidopa %> <%= t.estudiante.apellidoma %></td>
  <td><%= t.estudiante.carrera.nombrecarrera %></td>
  <td><%= t.user.nombre %> <%= t.user.apellidopa %> <t.user.apellidoma%></td>
  <td>
  <%if t.estado ==true %>
 <p class= "text-success"> Activo</p> 
 <%else%> 
 <p class="text-danger"> Eliminado</p>
<%end%>
  </td>
  <td>
  <%= link_to 'Mostrar', informe_url(t), class:"btn btn-outline-success  btn-sm" %>


    
	<% unless t.estado.nil? %>
	<% if t.estado == true %>
			
	  <%= link_to 'Eliminar', edit_informe_url(t), class: "btn btn-danger btn-sm",
                        method: :delete, data: {confirm: '¿Estas seguro?'} %>
    <% end %>
	  <% end %>
</td>
</tr>
<%end%>
<%end%>
</table>

app/views/informes/show.html.erb
<h1 class= "text-info pull-center"><u> Informe  <%= @informe.user.rol.descripcion %></h1> </u><br>
<%= link_to 'Generar PDF', informe_path(format: "pdf"), class:"btn btn-danger  btn-sm pull-right" %>


<h5>N° Informe : <%= @informe.id %></h5>
<h5>Fecha : <%= @informe.created_at.strftime("%d-%m-%Y = Hora: %H:%M:%S") %></h5><br>

<% if @informe.user.rol.descripcion=='Sicologo' %>
<p>Nombre de Profesional : <%= @informe.user.nombre %> <%= @informe.user.apellidopa %> <%= @informe.user.apellidoma%></p>
<p>Nombre Estudiante :  <%= @informe.estudiante.nombreestudiante %> <%= @informe.estudiante.apellidopa %> <%= @informe.estudiante.apellidoma%></p>
<p>Carrera : <%=@informe.estudiante.carrera.nombrecarrera%>

<br>
<h4><li><u>Habitos de Estudio</u></li></h4>

<table class= "table">
<tr><td>&nbsp &nbsp &nbsp &nbsp Si tiene problemas con materias, ¿que tan grave es?. </td> 
<td> <%= @informe.nota1 %></th> </tr>

<tr><th >&nbsp &nbsp &nbsp &nbsp¿Cómo considera que es la comprensión de los contenidos que estudia?.</th> 
<th> <%= @informe.nota2  %> </th></tr>

<tr><th> &nbsp &nbsp &nbsp &nbsp¿En relación al espacio físico de su lugar de estudio, ¿cómo lo califica?.</th>    
<th> <%= @informe.nota3 %></th> </tr>

<tr><th> &nbsp &nbsp &nbsp &nbsp¿Cómo es el tiempo que dedica a estudiar?.</th>   
<th> <%= @informe.nota4 %></th> </tr>
<tr><th>&nbsp &nbsp &nbsp &nbsp¿Cómo estima que son sus calificaciones en función de su estudio y esfuerzo?.</th>  
<th> <%= @informe.nota5  %> </th> </tr>
<tr class="bg-info"><th class="col-5">Promedio Habitos de Estudio: </th>
<th > <%=@informe.promhabitos%></th></tr>

</table>

<h4><li><u>Vocación</u></li></h4>
<table class= "table">
<td >&nbsp &nbsp &nbsp &nbsp¿Cómo considera que fue la elección que hizo de la carrera que cursa?.</td>
<td> <%= @informe.nota6 %></th> </td>
<tr><th >&nbsp &nbsp &nbsp &nbspCon respecto a su elección universitaria, ¿cómo la califica hoy? </th>
<th> <%= @informe.nota7 %></th> </tr>
<tr><th >&nbsp &nbsp &nbsp &nbsp¿Cómo  piensa que son los contenidos de las materias que imparte su carrera?. </th> 
<th> <%= @informe.nota8 %></th> </tr>
<tr><th>&nbsp &nbsp &nbsp &nbsp¿Qué tan drásticos cree que  han sido los cambios a lo largo del tiempo en relación a su vocación?.  </th>
<th> <%= @informe.nota9 %></th> </tr>
<tr><th >&nbsp &nbsp &nbsp &nbsp¿Cómo considera su nivel de vocación de elección universitaria antes de ingresar a la educación superior?. </th>
<th> <%= @informe.nota10 %></th> </tr>
<tr class="bg-info"><th class="col-5">Promedio Vocación: </th>
<th > <%=@informe.promvocacion%></th></tr>
</table>

<table class= "table">
<h4><li><u>Salud Fisica y Mental</u></li></h4>
<tr><th >&nbsp &nbsp &nbsp &nbsp¿Qué nivel de concentración presenta en la sala de clases?.</th>
<th> <%= @informe.nota11 %></th> </tr>
<tr><th >&nbsp &nbsp &nbsp &nbsp¿Cómo considera que es su salud mental luego de periodos prolongados de estudio?.</th>  
<th> <%= @informe.nota12 %></th> </tr>
<tr><th >&nbsp &nbsp &nbsp &nbspReferente a su salud física actual, ¿de qué manera cree que afecta su rendimiento académico?.</th>  
<th> <%= @informe.nota13 %></th> </tr>
<tr><th >&nbsp &nbsp &nbsp &nbsp¿Cómo se siente cuando debe expresar su opinión frente a sus compañeros?. </th> 
<th> <%= @informe.nota14 %></th> </tr>
<tr><th >&nbsp &nbsp &nbsp &nbsp¿Cómo estima que es la relación entre su salud física y mental?.</th>
<th> <%= @informe.nota15 %></th> </tr>
<tr class="bg-info"><th class="col-5">Promedio Salud Fisica y Mental: </th>
<th > <%=@informe.promsalud%></th></tr>
</table>
<h4><li><u>Observación</u></li></h4>
<p><%=@informe.observacion%><p>
<%end%>


<% if @informe.user.rol.descripcion=='Asistente Social' %>
<p>Nombre de Profesional : <%= @informe.user.nombre %> <%= @informe.user.apellidopa %> <%= @informe.user.apellidoma%></p>
<p>Nombre Estudiante :  <%= @informe.estudiante.nombreestudiante %> <%= @informe.estudiante.apellidopa %> <%= @informe.estudiante.apellidoma%></p>
<p>Carrera : <%=@informe.estudiante.carrera.nombrecarrera%>

<br>
<h4><li><u>Habitos de Estudio</u></li></h4>

<table class= "table">
<tr><th>&nbsp &nbsp &nbsp &nbsp Pensando en las últimas semanas, ¿cómo considera que es el tiempo que destinó para estudiar y preparar sus exámenes?. </th> 
<th> <%= @informe.nota1 %></th> </tr>

<tr><th >&nbsp &nbsp &nbsp &nbsp¿Cómo ha que sido el trabajo colaborativo con sus compañeros al momento de estudiar en los últimos días?.</th> 
<th> <%= @informe.nota2  %> </th></tr>

<tr><th> &nbsp &nbsp &nbsp &nbsp¿Cómo califica la atención- concentración al momento de estudiar?</th>    
<th> <%= @informe.nota3 %></th> </tr>

<tr><th> &nbsp &nbsp &nbsp &nbspEn los últimos días, ¿estima que los problemas afectivos han perjudicado su rendimiento?.</th>   
<th> <%= @informe.nota4 %></th> </tr>
<tr><th>&nbsp &nbsp &nbsp &nbspEn el estudio de las últimas evaluaciones, ¿cómo consideras que ha trabajado con métodos de estudio?(mapas conceptuales, resumen, etc.)</th>  
<th> <%= @informe.nota5  %> </th> </tr>
<tr class="bg-info"><th class="col-5">Promedio Habitos de Estudio: </th>
<th > <%=@informe.promhabitos%></th></tr>

</table>

<h4><li><u>Vocación</u></li></h4>
<table class= "table">
<tr><th >&nbsp &nbsp &nbsp &nbspA partir de lo aprendido en el último tiempo, ¿cómo cree que es la relación entre su vocación y preparación?.</th>
<th> <%= @informe.nota6 %></th> </tr>
<tr><th >&nbsp &nbsp &nbsp &nbspEn los últimos días, ¿cómo se ha sentido con la decisión de estudiar la carrera que cursa?. </th>
<th> <%= @informe.nota7 %></th> </tr>
<tr><th >&nbsp &nbsp &nbsp &nbsp¿Cómo considera la preparación de las clases de los docentes?. </th> 
<th> <%= @informe.nota8 %></th> </tr>
<tr><th >&nbsp &nbsp &nbsp &nbsp ¿Cómo estima que es la relación de sus notas versus su preparación en el último tiempo?  </th>
<th> <%= @informe.nota9 %></th> </tr>
<tr><th >&nbsp &nbsp &nbsp &nbsp¿Cómo ha sido el aporte social para el desarrollo vocacional?. </th>
<th> <%= @informe.nota10 %></th> </tr>
<tr class="bg-info"><th class="col-5">Promedio Vocación: </th>
<th > <%=@informe.promvocacion%></th></tr>
</table>

<table class= "table">
<h4><li><u>Salud Fisica y Mental</u></li></h4>
<tr><th >&nbsp &nbsp &nbsp &nbspEn la Sala de clases, si tiene problemas de concentracion, que tan frecuentes son ?</th>
<th> <%= @informe.nota11 %></th> </tr>
<tr><th >&nbsp &nbsp &nbsp &nbsp¿Siente malestar fisico o emocional al estar en la sala de clases con mas personas ?</th>  
<th> <%= @informe.nota12 %></th> </tr>
<tr><th >&nbsp &nbsp &nbsp &nbsp¿Ha dejado la actividad fisica o los estudios, solo por que no se siente bien emocionalmente ?</th>  
<th> <%= @informe.nota13 %></th> </tr>
<tr><th >&nbsp &nbsp &nbsp &nbsp¿Si tiene alteraciones de sueño, que tan frecuentes son ?. </th> 
<th> <%= @informe.nota14 %></th> </tr>
<tr><th >&nbsp &nbsp &nbsp &nbsp¿Es capaz de expresar abiertamiente su opinion y compartir con compañeros ?.</th>
<th> <%= @informe.nota15 %></th> </tr>
<tr class="bg-info"><th class="col-5">Promedio Salud Fisica y Mental: </th>
<th > <%=@informe.promsalud%></th></tr>
</table>
<h4><li><u>Observación</u></li></h4>
<p><%=@informe.observacion%><p>
<%end%>


<% if @informe.user.rol.descripcion=='Tutor' %>
<p>Nombre de Profesional : <%= @informe.user.nombre %> <%= @informe.user.apellidopa %> <%= @informe.user.apellidoma%></p>
<p>Nombre Estudiante :  <%= @informe.estudiante.nombreestudiante %> <%= @informe.estudiante.apellidopa %> <%= @informe.estudiante.apellidoma%></p>
<p>Carrera : <%=@informe.estudiante.carrera.nombrecarrera%>

<br>
<h4><li><u>Habitos de Estudio</u></li></h4>

<table class= "table">
<tr><th>&nbsp &nbsp &nbsp &nbsp Referente al tiempo que ha dedicado al estudio estos últimos días, ¿cómo considera que han sido los resultados académicos?. </th> 
<th> <%= @informe.nota1 %></th> </tr>

<tr><th >&nbsp &nbsp &nbsp &nbspEn relación a la concentración cuando estudia, ¿qué nivel considera que logra alcanzar?.</th> 
<th> <%= @informe.nota2  %> </th></tr>

<tr><th> &nbsp &nbsp &nbsp &nbsp¿Cómo considera que es su organización para estudiar y realizar trabajos? (horario de repaso, investigación, etc.)</th>    
<th> <%= @informe.nota3 %></th> </tr>

<tr><th> &nbsp &nbsp &nbsp &nbsp¿Cómo es el espacio que destina para poder estudiar y realizar trabajos?.</th>   
<th> <%= @informe.nota4 %></th> </tr>
<tr><th>&nbsp &nbsp &nbsp &nbsp¿Cómo considera que es su comprensión cuando estudia o realiza trabajos en horarios no adecuados? (día previo a una prueba o entrega de trabajos, en la madrugada, etc.)</th>  
<th> <%= @informe.nota5  %> </th> </tr>
<tr class="bg-info"><th class="col-5">Promedio Habitos de Estudio: </th>
<th > <%=@informe.promhabitos%></th></tr>

</table>

<h4><li><u>Vocación</u></li></h4>
<table class= "table">
<tr><th >&nbsp &nbsp &nbsp &nbsp¿Cómo estima que ha sido su actitud al asistir a clases?.</th>
<th> <%= @informe.nota6 %></th> </tr>
<tr><th >&nbsp &nbsp &nbsp &nbspEn función a las clases asistidas, ¿cómo cumplen con sus expectativas vocacionales? </th>
<th> <%= @informe.nota7 %></th> </tr>
<tr><th >&nbsp &nbsp &nbsp &nbsp¿Cómo se ha sentido en los últimos días respecto a su decisión de cursar esta carrera universitaria?</th> 
<th> <%= @informe.nota8 %></th> </tr>
<tr><th >&nbsp &nbsp &nbsp &nbsp¿Cómo se siente luego de obtener una calificación que no esperaba?  </th>
<th> <%= @informe.nota9 %></th> </tr>
<tr><th >&nbsp &nbsp &nbsp &nbspEn el último tiempo, ¿cómo considera que influye su vocación en el futuro laboral?. </th>
<th> <%= @informe.nota10 %></th> </tr>
<tr class="bg-info"><th class="col-5">Promedio Vocación: </th>
<th > <%=@informe.promvocacion%></th></tr>
</table>

<table class= "table">
<h4><li><u>Salud Fisica y Mental</u></li></h4>
<tr><th >&nbsp &nbsp &nbsp &nbsp¿Cómo cree que se relaciona con sus compañeros al momento de estudiar, aclarar dudas o solicitar contenidos?</th>
<th> <%= @informe.nota11 %></th> </tr>
<tr><th >&nbsp &nbsp &nbsp &nbsp¿Cómo considera que se ha alimentado estos últimos días en razón a su estado de ánimo?</th>  
<th> <%= @informe.nota12 %></th> </tr>
<tr><th >&nbsp &nbsp &nbsp &nbspEn razón de las actividades físicas y/o  recreativas, ¿cómo cree que han sido éstas en el último periodo?</th>  
<th> <%= @informe.nota13 %></th> </tr>
<tr><th >&nbsp &nbsp &nbsp &nbsp¿Cómo sientes que es el aporte que brinda su grupo de compañeros y/o amigos en su salud física y mental? </th> 
<th> <%= @informe.nota14 %></th> </tr>
<tr><th >&nbsp &nbsp &nbsp &nbsp¿Cuál crees que es el aporte que entrega su estado mental al rendimiento académico?</th>
<th> <%= @informe.nota15 %></th> </tr>
<tr class="bg-info"><th class="col-5">Promedio Salud Fisica y Mental: </th>
<th > <%=@informe.promsalud%></th></tr>
</table>
<h4><li><u>Observación</u></li></h4>
<p><%=@informe.observacion%><p>
<%end%>



<% if @informe.user.rol.descripcion=='Jefe de Carrera' %>
<p>Nombre de Profesional : <%= @informe.user.nombre %> <%= @informe.user.apellidopa %> <%= @informe.user.apellidoma%></p>
<p>Nombre Estudiante :  <%= @informe.estudiante.nombreestudiante %> <%= @informe.estudiante.apellidopa %> <%= @informe.estudiante.apellidoma%></p>
<p>Carrera : <%=@informe.estudiante.carrera.nombrecarrera%>

<h4><li><u>Observación</u></li></h4>
<p><%=@informe.observacion%><p>
<br><br><br><br>

<%end%>